### ISSUE TITLE
Issue on page /src/text/1_part_i/2.1.html -- erroneous examples.

### ISSUE THREAD

**Issue by abuseofnotation** [simply-logical/simply-logical#20] opened 2024-10-07 09:20 UTC
As you yourself mentioned in one of the notes, the examples are very outdated.

Besides the fact that you should replace "man" with "human" in examples like this one:

married;bachelor:-man,adult 

(it is no minor matter, as people who are learning something new are very sensitive to confusions like this)

you also say 

:-man,woman.

which is debatable at best 

and 

has_wife:-man,married.

which is plain wrong.

**Comment by flach** [comment] 2024-10-09 15:31
Thanks for pointing this out, this has been raised before (https://github.com/simply-logical/simply-logical/issues/16) and I agree. I just haven't found the time to address this.

**Comment by So-Cool** [comment] 2024-12-16 16:57
duplicate of #16

**Closed as not planned by So-Cool** 2024-12-16 16:57 UTC
